repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: local
    hooks:
    -   id: bib-tidy
        name: Tidy BibTex
        entry: .pre-commit-hooks.d/bib-tidy.sh
        language: script
        types: [text]

    -   id: rm-tex
        name: Remove LaTeX Auxiliary Files
        entry: .pre-commit-hooks.d/rm-tex.sh
        language: script
        types: [text]

-   repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.24.4
    hooks:
    -   id: latexindent